extends: 'airbnb-base'

env:
  node: true
  browser: true

parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    forOf: true
    jsx: true
    es6: true
    experimentalObjectRestSpread: true

rules:
  object-curly-spacing : 0
  arrow-body-style: 0
  no-console: 0
  strict: [0]
  no-underscore-dangle: [error, { allow: [_id] }]
  prefer-rest-params: [0]
  import/no-extraneous-dependencies: off
  import/no-unresolved: 0
  global-require: 0
  max-len: 0
  comma-dangle: 0
  indent: 2
  prefer-template: 0
  react/prop-types: 0
  react/jsx-indent-props : 0
  react/jsx-closing-bracket-location : 0
plugins: [ react ]
globals:
  __DEVSERVER__: true
  __DEVCLIENT__: true
