export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const CREATE_TOPIC_REQUEST = 'CREATE_TOPIC_REQUEST';
export const CREATE_TOPIC_FAILURE = 'CREATE_TOPIC_FAILURE';
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
export const CREATE_TOPIC_DUPLICATE = 'CREATE_TOPIC_DUPLICATE';
export const GET_TOPICS = 'GET_TOPICS';
export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILURE = 'GET_TOPICS_FAILURE';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const DESTROY_TOPIC = 'DESTROY_TOPIC';
export const TYPING = 'TYPING';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

export const CREATE_SHOPLIST_REQUEST = 'CREATE_SHOPLIST_REQUEST';
export const CREATE_SHOPLIST_SUCCESS = 'CREATE_SHOPLIST_SUCCESS';
export const CREATE_SHOPLIST_FAILURE = 'CREATE_SHOPLIST_FAILURE';
export const CREATE_SHOPLIST_DUPLICATE = 'CREATE_SHOPLIST_DUPLICATE';

export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const PRODUCTS_LENGTH = 'PRODUCTS_LENGTH';
export const DELETE_NEW_PRODUCT = 'DELETE_NEW_PRODUCT';

export const CHANGE_PRODUCT_CODE = 'CHANGE_PRODUCT_CODE';
export const PRODUCT_CODE_LENGTH = 'PRODUCT_CODE_LENGTH';

export const SHOP_LIST_CUSTOM = 'SHOP_LIST_CUSTOM';
export const SHOP_LIST_IS_EDITING = 'SHOP_LIST_IS_EDITING';

export const GET_SHOPLIST = 'GET_SHOPLIST';
export const GET_SHOPLIST_REQUEST = 'GET_SHOPLIST_REQUEST';
export const GET_SHOPLIST_SUCCESS = 'GET_SHOPLIST_SUCCESS';
export const GET_SHOPLIST_FAILURE = 'GET_SHOPLIST_FAILURE';

export const SHOPLIST_IS_CREATING = 'SHOPLIST_IS_CREATING';
// export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
// export const LOAD_CATEGORIES_ERROR = 'LOAD_CATEGORIES_ERROR';
// export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
